-- 코드를 입력하세요

SELECT T1.* , T2.PRODUCT_NAME 
FROM 
(
    SELECT CATEGORY AS CATEGORY, 
    MAX(PRICE) AS MAX_PRICE   
    FROM FOOD_PRODUCT 
    GROUP BY CATEGORY 
    HAVING CATEGORY IN ('과자', '국' , '김치' , '식용유')) T1 
    
LEFT JOIN 
(SELECT CATEGORY, PRODUCT_NAME , PRICE 
 FROM FOOD_PRODUCT) T2 
 ON T1.MAX_PRICE = T2.PRICE 
 AND  T1.CATEGORY = T2.CATEGORY

ORDER BY MAX_PRICE DESC