-- 코드를 입력하세요
SELECT T1.PRODUCT_ID, T2.PRODUCT_NAME, 
SUM(AMOUNT) * T2.PRICE AS TOTAL_SALES
FROM FOOD_ORDER AS T1
JOIN FOOD_PRODUCT AS T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE T1.PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;